# Generated by Django 5.0 on 2025-03-24 01:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('additional_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_monthly', models.BooleanField(default=False)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('dinero_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dinero_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuadre_realizado', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('fecha', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ParkingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('placa', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cascos', models.IntegerField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('monthly_expiry', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiclecategory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parkingticket',
            constraint=models.UniqueConstraint(condition=models.Q(('exit_time__isnull', True)), fields=('placa',), name='unique_active_plate'),
        ),
    ]
