# Generated by custom script
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_add_tenant_to_vehiclecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='tenant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ] 