# Generated by custom script
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_add_tenant_to_parkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='parkingticket',
            constraint=models.UniqueConstraint(condition=models.Q(exit_time__isnull=True), fields=('tenant', 'placa'), name='unique_active_plate_per_tenant'),
        ),
    ] 