# Generated by custom script
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_add_tenant_to_parkingticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='caja',
            unique_together={('tenant', 'fecha', 'tipo')},
        ),
    ] 