# Generated by Django 5.1.3 on 2025-07-12 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_add_tenant_to_caja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Parqueadero', 'verbose_name_plural': 'Parqueaderos'},
        ),
        migrations.AlterModelOptions(
            name='parkingticket',
            options={'ordering': ['-entry_time'], 'verbose_name': 'Ticket de Parqueadero', 'verbose_name_plural': 'Tickets de Parqueadero'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'verbose_name': 'Categoría de Vehículo', 'verbose_name_plural': 'Categorías de Vehículos'},
        ),
        migrations.RemoveConstraint(
            model_name='parkingticket',
            name='unique_active_plate',
        ),
        migrations.AlterField(
            model_name='caja',
            name='cuadre_realizado',
            field=models.BooleanField(default=False, verbose_name='Cuadre realizado'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='dinero_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero final'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='dinero_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dinero inicial'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='empresa',
            field=models.CharField(max_length=255, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/', verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='cascos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cascos'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiclecategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='monthly_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento mensual'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='placa',
            field=models.CharField(max_length=20, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cajero', 'Cajero'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='cajero', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='additional_hour_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tarifa hora adicional'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='first_hour_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tarifa primera hora'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='is_monthly',
            field=models.BooleanField(default=False, verbose_name='Es mensual'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa mensual'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
