# Generated by Django 5.1.3 on 2025-07-13 19:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_userprofile_unique_user_per_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fondo fijo inicial')),
                ('monto_real_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto real contado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('firma_cierre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma/confirmación de cierre')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10, verbose_name='Estado del turno')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario apertura')),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario cierre')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10, verbose_name='Tipo de movimiento')),
                ('categoria', models.CharField(choices=[('parqueo', 'Parqueo'), ('venta', 'Venta de productos'), ('penalidad', 'Penalidad'), ('compra', 'Compra menor'), ('anticipo', 'Anticipo'), ('devolucion', 'Devolución'), ('otro', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('datafono', 'Datáfono'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20, verbose_name='Forma de pago')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de vehículo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('caja_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='parking.cajaturno', verbose_name='Turno de caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
