# Generated by Django 5.1.3 on 2025-07-14 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_cajaturno_cajamovimiento_delete_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del módulo')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('permission_change', 'Cambio de permisos'), ('role_assignment', 'Asignación de rol'), ('user_creation', 'Creación de usuario'), ('user_edit', 'Edición de usuario'), ('user_deletion', 'Eliminación de usuario')], max_length=50, verbose_name='Acción')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Acceso',
                'verbose_name_plural': 'Bitácoras de Acceso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_system', models.BooleanField(default=False, verbose_name='Rol del sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Rol Personalizado',
                'verbose_name_plural': 'Roles Personalizados',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del permiso')),
                ('code', models.CharField(max_length=50, verbose_name='Código del permiso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['module__order', 'name'],
                'unique_together': {('module', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.permission', verbose_name='Permiso')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.customrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'ordering': ['role__name', 'permission__module__order', 'permission__name'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True, verbose_name='Permitido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.permission', verbose_name='Permiso')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.userprofile', verbose_name='Perfil de Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
                'ordering': ['permission__module__order', 'permission__name'],
                'unique_together': {('user_profile', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Rol principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.customrole', verbose_name='Rol')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.userprofile', verbose_name='Perfil de Usuario')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'ordering': ['-is_primary', 'role__name'],
                'unique_together': {('user_profile', 'role')},
            },
        ),
    ]
