# Generated by Django 5.1.3 on 2025-07-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_module_accesslog_customrole_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto recibido'),
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vuelto'),
        ),
    ]
