# Generated by Django 5.1.3 on 2025-08-01 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_parkingticket_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la moneda')),
                ('code', models.CharField(max_length=10, verbose_name='Código de la moneda')),
                ('symbol', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Decimales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, verbose_name='Moneda por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del impuesto')),
                ('code', models.CharField(max_length=10, verbose_name='Código del impuesto')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Impuesto por defecto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Tipos de Impuestos',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_tax_by_default', models.BooleanField(default=False, verbose_name='Aplicar impuesto por defecto')),
                ('include_tax_in_ticket', models.BooleanField(default=False, verbose_name='Incluir impuesto en ticket')),
                ('show_tax_breakdown', models.BooleanField(default=True, verbose_name='Mostrar desglose de impuesto')),
                ('thousand_separator', models.CharField(default='.', max_length=1, verbose_name='Separador de miles')),
                ('decimal_separator', models.CharField(default=',', max_length=1, verbose_name='Separador decimal')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la empresa')),
                ('receipt_footer_text', models.TextField(blank=True, verbose_name='Texto pie de página en recibos')),
                ('timezone', models.CharField(default='America/Bogota', max_length=50, verbose_name='Zona horaria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.currency', verbose_name='Moneda por defecto')),
                ('default_tax_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.taxtype', verbose_name='Impuesto por defecto')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
    ]
