# Generated by Django 5.1.3 on 2025-08-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_notificationconfig_scheduleconfig_spaceconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TariffConfig',
        ),
        migrations.DeleteModel(
            name='ScheduleConfig',
        ),
        migrations.DeleteModel(
            name='NotificationConfig',
        ),
        migrations.DeleteModel(
            name='SpaceConfig',
        ),
    ]
